# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/yuki_cjm/big homework/BasicInterpreter-2025-main/BasicInterpreter-2025-main"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/yuki_cjm/big homework/BasicInterpreter-2025-main/BasicInterpreter-2025-main"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/yuki_cjm/big homework/BasicInterpreter-2025-main/BasicInterpreter-2025-main/CMakeFiles" "/home/yuki_cjm/big homework/BasicInterpreter-2025-main/BasicInterpreter-2025-main//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/yuki_cjm/big homework/BasicInterpreter-2025-main/BasicInterpreter-2025-main/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code

# Build rule for target.
code: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 code
.PHONY : code

# fast build rule for target.
code/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/build
.PHONY : code/fast

#=============================================================================
# Target rules for targets named attached_test

# Build rule for target.
attached_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attached_test
.PHONY : attached_test

# fast build rule for target.
attached_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attached_test.dir/build.make CMakeFiles/attached_test.dir/build
.PHONY : attached_test/fast

#=============================================================================
# Target rules for targets named scope_test

# Build rule for target.
scope_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scope_test
.PHONY : scope_test

# fast build rule for target.
scope_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scope_test.dir/build.make CMakeFiles/scope_test.dir/build
.PHONY : scope_test/fast

AttachedTest.o: AttachedTest.cpp.o
.PHONY : AttachedTest.o

# target to build an object file
AttachedTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attached_test.dir/build.make CMakeFiles/attached_test.dir/AttachedTest.cpp.o
.PHONY : AttachedTest.cpp.o

AttachedTest.i: AttachedTest.cpp.i
.PHONY : AttachedTest.i

# target to preprocess a source file
AttachedTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attached_test.dir/build.make CMakeFiles/attached_test.dir/AttachedTest.cpp.i
.PHONY : AttachedTest.cpp.i

AttachedTest.s: AttachedTest.cpp.s
.PHONY : AttachedTest.s

# target to generate assembly for a file
AttachedTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attached_test.dir/build.make CMakeFiles/attached_test.dir/AttachedTest.cpp.s
.PHONY : AttachedTest.cpp.s

ScopeTest.o: ScopeTest.cpp.o
.PHONY : ScopeTest.o

# target to build an object file
ScopeTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scope_test.dir/build.make CMakeFiles/scope_test.dir/ScopeTest.cpp.o
.PHONY : ScopeTest.cpp.o

ScopeTest.i: ScopeTest.cpp.i
.PHONY : ScopeTest.i

# target to preprocess a source file
ScopeTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scope_test.dir/build.make CMakeFiles/scope_test.dir/ScopeTest.cpp.i
.PHONY : ScopeTest.cpp.i

ScopeTest.s: ScopeTest.cpp.s
.PHONY : ScopeTest.s

# target to generate assembly for a file
ScopeTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scope_test.dir/build.make CMakeFiles/scope_test.dir/ScopeTest.cpp.s
.PHONY : ScopeTest.cpp.s

src/Basic.o: src/Basic.cpp.o
.PHONY : src/Basic.o

# target to build an object file
src/Basic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Basic.cpp.o
.PHONY : src/Basic.cpp.o

src/Basic.i: src/Basic.cpp.i
.PHONY : src/Basic.i

# target to preprocess a source file
src/Basic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Basic.cpp.i
.PHONY : src/Basic.cpp.i

src/Basic.s: src/Basic.cpp.s
.PHONY : src/Basic.s

# target to generate assembly for a file
src/Basic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Basic.cpp.s
.PHONY : src/Basic.cpp.s

src/Expression.o: src/Expression.cpp.o
.PHONY : src/Expression.o

# target to build an object file
src/Expression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Expression.cpp.o
.PHONY : src/Expression.cpp.o

src/Expression.i: src/Expression.cpp.i
.PHONY : src/Expression.i

# target to preprocess a source file
src/Expression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Expression.cpp.i
.PHONY : src/Expression.cpp.i

src/Expression.s: src/Expression.cpp.s
.PHONY : src/Expression.s

# target to generate assembly for a file
src/Expression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Expression.cpp.s
.PHONY : src/Expression.cpp.s

src/Lexer.o: src/Lexer.cpp.o
.PHONY : src/Lexer.o

# target to build an object file
src/Lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Lexer.cpp.o
.PHONY : src/Lexer.cpp.o

src/Lexer.i: src/Lexer.cpp.i
.PHONY : src/Lexer.i

# target to preprocess a source file
src/Lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Lexer.cpp.i
.PHONY : src/Lexer.cpp.i

src/Lexer.s: src/Lexer.cpp.s
.PHONY : src/Lexer.s

# target to generate assembly for a file
src/Lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Lexer.cpp.s
.PHONY : src/Lexer.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Program.o: src/Program.cpp.o
.PHONY : src/Program.o

# target to build an object file
src/Program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Program.cpp.o
.PHONY : src/Program.cpp.o

src/Program.i: src/Program.cpp.i
.PHONY : src/Program.i

# target to preprocess a source file
src/Program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Program.cpp.i
.PHONY : src/Program.cpp.i

src/Program.s: src/Program.cpp.s
.PHONY : src/Program.s

# target to generate assembly for a file
src/Program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Program.cpp.s
.PHONY : src/Program.cpp.s

src/Recorder.o: src/Recorder.cpp.o
.PHONY : src/Recorder.o

# target to build an object file
src/Recorder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Recorder.cpp.o
.PHONY : src/Recorder.cpp.o

src/Recorder.i: src/Recorder.cpp.i
.PHONY : src/Recorder.i

# target to preprocess a source file
src/Recorder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Recorder.cpp.i
.PHONY : src/Recorder.cpp.i

src/Recorder.s: src/Recorder.cpp.s
.PHONY : src/Recorder.s

# target to generate assembly for a file
src/Recorder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Recorder.cpp.s
.PHONY : src/Recorder.cpp.s

src/Statement.o: src/Statement.cpp.o
.PHONY : src/Statement.o

# target to build an object file
src/Statement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Statement.cpp.o
.PHONY : src/Statement.cpp.o

src/Statement.i: src/Statement.cpp.i
.PHONY : src/Statement.i

# target to preprocess a source file
src/Statement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Statement.cpp.i
.PHONY : src/Statement.cpp.i

src/Statement.s: src/Statement.cpp.s
.PHONY : src/Statement.s

# target to generate assembly for a file
src/Statement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Statement.cpp.s
.PHONY : src/Statement.cpp.s

src/Token.o: src/Token.cpp.o
.PHONY : src/Token.o

# target to build an object file
src/Token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Token.cpp.o
.PHONY : src/Token.cpp.o

src/Token.i: src/Token.cpp.i
.PHONY : src/Token.i

# target to preprocess a source file
src/Token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Token.cpp.i
.PHONY : src/Token.cpp.i

src/Token.s: src/Token.cpp.s
.PHONY : src/Token.s

# target to generate assembly for a file
src/Token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/Token.cpp.s
.PHONY : src/Token.cpp.s

src/VarState.o: src/VarState.cpp.o
.PHONY : src/VarState.o

# target to build an object file
src/VarState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/VarState.cpp.o
.PHONY : src/VarState.cpp.o

src/VarState.i: src/VarState.cpp.i
.PHONY : src/VarState.i

# target to preprocess a source file
src/VarState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/VarState.cpp.i
.PHONY : src/VarState.cpp.i

src/VarState.s: src/VarState.cpp.s
.PHONY : src/VarState.s

# target to generate assembly for a file
src/VarState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/VarState.cpp.s
.PHONY : src/VarState.cpp.s

src/utils/Error.o: src/utils/Error.cpp.o
.PHONY : src/utils/Error.o

# target to build an object file
src/utils/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/utils/Error.cpp.o
.PHONY : src/utils/Error.cpp.o

src/utils/Error.i: src/utils/Error.cpp.i
.PHONY : src/utils/Error.i

# target to preprocess a source file
src/utils/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/utils/Error.cpp.i
.PHONY : src/utils/Error.cpp.i

src/utils/Error.s: src/utils/Error.cpp.s
.PHONY : src/utils/Error.s

# target to generate assembly for a file
src/utils/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/utils/Error.cpp.s
.PHONY : src/utils/Error.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... attached_test"
	@echo "... code"
	@echo "... scope_test"
	@echo "... AttachedTest.o"
	@echo "... AttachedTest.i"
	@echo "... AttachedTest.s"
	@echo "... ScopeTest.o"
	@echo "... ScopeTest.i"
	@echo "... ScopeTest.s"
	@echo "... src/Basic.o"
	@echo "... src/Basic.i"
	@echo "... src/Basic.s"
	@echo "... src/Expression.o"
	@echo "... src/Expression.i"
	@echo "... src/Expression.s"
	@echo "... src/Lexer.o"
	@echo "... src/Lexer.i"
	@echo "... src/Lexer.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Program.o"
	@echo "... src/Program.i"
	@echo "... src/Program.s"
	@echo "... src/Recorder.o"
	@echo "... src/Recorder.i"
	@echo "... src/Recorder.s"
	@echo "... src/Statement.o"
	@echo "... src/Statement.i"
	@echo "... src/Statement.s"
	@echo "... src/Token.o"
	@echo "... src/Token.i"
	@echo "... src/Token.s"
	@echo "... src/VarState.o"
	@echo "... src/VarState.i"
	@echo "... src/VarState.s"
	@echo "... src/utils/Error.o"
	@echo "... src/utils/Error.i"
	@echo "... src/utils/Error.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

